document.write('<nav class="sb-topnav navbar navbar-expand navbar-dark bg-success">');
document.write('    <!-- Navbar Brand-->');
document.write('    <a class="navbar-brand ps-3" href="index.html">IoT Aforos UdeA</a>');
document.write('    <!-- Sidebar Toggle-->');
document.write('    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0 align-items-center" id="sidebarToggle"');
document.write('        href="#!"><i class="fas fa-bars text-white"></i></button>');
document.write('    <!-- Navbar Search-->');
document.write('    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">');
document.write('        <div class="input-group">');
document.write('            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..."');
document.write('                aria-describedby="btnNavbarSearch" />');
document.write('            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i');
document.write('                    class="fas fa-search"></i></button>');
document.write('        </div>');
document.write('    </form>');
document.write('    <!-- Navbar-->');
document.write('    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">');
document.write('        <li class="nav-item dropdown ">');
document.write('            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"');
document.write('                aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>');
document.write('            <ul class="dropdown-menu dropdown-menu-end " aria-labelledby="navbarDropdown">');
document.write('                <li><a class="dropdown-item" href="#!">Configuraciones</a></li>');
document.write('                <li><a class="dropdown-item" href="#!">Registrar</a></li>');
document.write('                <li>');
document.write('                    <hr class="dropdown-divider" />');
document.write('                </li>');
document.write('                <li><a class="dropdown-item" href="#!">Salir</a></li>');
document.write('            </ul>');
document.write('        </li>');
document.write('    </ul>');
document.write('</nav>');
