document.write('<div id="layoutSidenav_nav">');
document.write('    <nav class="sb-sidenav accordion sb-sidenav-dark bg-img" id="sidenavAccordion">');
document.write('        <div class="sb-sidenav-menu">');
document.write('            <div class="nav">');
document.write('                <div class="sb-sidenav-menu-heading text-white"><b>Tablero</b></div>');
document.write('                <a class="nav-link text-white" href="index.html">');
document.write('                    <div class="sb-nav-link-icon "><i class="fas fa-tachometer-alt text-white"></i></div>');
document.write('                    Mediciones');
document.write('                </a>');
document.write('                <div class="sb-sidenav-menu-heading text-white"><b>Admin</b></div>');
document.write('                <a class="nav-link text-white" href="add-room.html">');
document.write('                    <div class="sb-nav-link-icon "><i class="fas fa-user-alt text-white"></i></div>');
document.write('                    Agregar espacio');
document.write('                </a>');
document.write('');
document.write('            </div>');
document.write('        </div>');
document.write('        <div class="sb-sidenav-footer bg-logo">');
document.write('            <div class="big ">.</div>');
document.write('            <div class="big ">.</div>');
document.write('            .');
document.write('');
document.write('');
document.write('        </div>');
document.write('    </nav>');
document.write('</div>');
